export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'


export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDER_REQUEST'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDER_FAIL'